### ISSUE TITLE
please write a document ,how to use it

### ISSUE THREAD

**Issue by dontnoun** [cmcpasserby/MayaCharm#1]
please write a document ,how to use it, like:
which version of pycharm maya  require, 32bit or 64bit
pycharm project interpreter settings?

host name is 'localhost' or '127.0.0.1'?

buffer size? script tpye? eg:
import maya.cmds as cmds
cmds.commandPort(name= '127.0.0.1:1234', bufferSize = 128000, stp='python')

thanks!

PS: it does not work for pycharm5. , maya2013
tried to run?
import maya.cmds as cmds
def main( ):
    cmds.polyCube()
    #for ii in dir(cmds): print ii

if __name__ == '__main__':
    main( )
get error info:
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    main( )
  File "test.py", line 8, in main
    cmds.polyCube()
AttributeError: 'module' object has no attribute 'polyCube'

**Comment by cmcpasserby** [comment]
Sorry for the late reply, which branch did you try to get it from, or were you using the .jar file i linked?
The current stable wont work with the stp='python' option and you should be using master anyways unless you are contributing.

i built and tested with 5.x both community and pro editions with Maya 2015 and 2012 but it should work on all Maya versions post 2012.

For setup just install the jar file with the plugin manager than go to "Settings>Other Settings>MayaCharm". It should let you define a port and hostname there the defualts of local host and port 4434 should be good for most users unless you are running pycharm and maya on different machines. It will provide the code you need to put in Maya's usersetup in this window as well.
`import maya.cmds as cmds
if not cmds.commandPort(':4434', q=True):
    cmds.commandPort(n=':4434') `

Once that is done it should just work and you should be able to create MayaCharm Run Configurations like you would any other run configuration.
