### ISSUE TITLE
MayaCharm debugger for CLion

### ISSUE THREAD

**Issue by megaes** [cmcpasserby/MayaCharm#15]
Hi!

Is it possible to have subj? :)

**Comment by cmcpasserby** [comment]
the C++ API for Maya is a whole other monster, and would be a whole other product, its been a while but i was pretty sure Visual Studio could breakpoint debug Maya plugins out of the box and i would assume CLion can do the same.

**Comment by megaes** [comment]
I mean, CLion supports Python and  MayaCharm runner works there and what about MayaCharm debugger...

**Comment by cmcpasserby** [comment]
The debugger is extending from the remote debugger in PyCharm which only exists in the pro edition of it.
