### ISSUE TITLE
PyCharm Community 2017.3.4 donot have MayaCharm Debugger

### ISSUE THREAD

**Issue by ZhanPeng** [cmcpasserby/MayaCharm#16]
like title, using plugins store install mayacharm

**Comment by cmcpasserby** [comment]
the debugger only supports the pro version of PyCharm, what version of PyCharm do you use?

**Comment by ZhanPeng** [comment]
I use PyCharm Professional, but my friend used PyCharm Community. Why debugger only supported pro version?

**Comment by cmcpasserby** [comment]
It extends and wraps the remote debugger already in PyCharm Professional, been looking at a other method but that is how it works for now.

**Comment by ZhanPeng** [comment]
thank you. I will try to fix this in my free time.
