### ISSUE TITLE
Add debugger port options to general settings

### ISSUE THREAD

**Issue by j0yu** [cmcpasserby/MayaCharm#17]
I noticed in #11 , the debugger settings I made in the main MayaCharm settings were similar to those already existing in [MayaCharmDebugForm](https://github.com/cmcpasserby/MayaCharm/blob/6f4b065377bc2828f9b6df6bac4ed87efece0d20/src/ca/rightsomegoodgames/mayacharm/run/debug/MayaCharmDebugForm.form).

Maybe I can make the:
* Host Name
* Port Number
options inherit from a "global" set of options.

Those "global" options can then be used for "attach to local process" in #11

**Comment by cmcpasserby** [comment]
this is all getting overhauled in the 3.0 version and port to kotlin
