### ISSUE TITLE
No autocomplete

### ISSUE THREAD

**Issue by iMitrandir** [cmcpasserby/MayaCharm#20]
Hi!  Could you help me please, i have a problem - the autocompletion of code doesn't working.  The scripts are working but without this option it's very hard to code :( Maybe i've missed something in the setup process?
![1536787028093](https://user-images.githubusercontent.com/35339973/45453839-a0223900-b6ea-11e8-8987-6366b8d72431.jpg)

**Comment by cmcpasserby** [comment]
yeah this plug-in does not include the auto complete stubs, to get them grab the maya devkit, then in the interpreter settings of PyCharm add maya's mayaPy interpreter and add the path to the completion files in the devkit to to interpreter paths.

**Comment by cmcpasserby** [comment]
devkit downloads are near the bottom of this page
https://www.autodesk.com/developer-network/platform-technologies/maya

**Comment by iMitrandir** [comment]
Well, i don't use pycharm, i'm using Intellij idea , and sadly there is nothing related to how to set up this autocompletion (( i've digged through alot of info, but couldn't find anything helpful ( though i'm a newbie in python and maybe for some pro it's a simple task). So if you could find some time, could you make tutorial on how to set up this autocompletion, it'll be very helpful for other starters like myself who want to use this plugin

**Comment by cmcpasserby** [comment]
Yeah if I do that it would be a while from now since I am on vacation for a few weeks.

**Comment by iMitrandir** [comment]
Ok, thank you! I'll try again to setup maybe something would works out.
