### ISSUE TITLE
Bring back the option to Attach to maya but not execute.

### ISSUE THREAD

**Issue by cmcpasserby** [cmcpasserby/MayaCharm#27]
Removing this option broke some workflows, and made it harder for people that are triggering there code via Maya's UI and not using the run config to execute a file.

**Comment by chadlichty** [comment]
Hi Chris.  Yes, please bring this back.

**Comment by cmcpasserby** [comment]
i am going to have this implemented in the next version, i have it integrated with the current `Attach to Process` menu in d3d7d279aa892c7c8ca5a2a1c012b3c0cc13252c

**Comment by cmcpasserby** [comment]
This fix will be in the plugin repo in the next 2 to 3 days, and after that PyCharm will attach to maya like it would any other python process.
