### ISSUE TITLE
Not finding maya.bin process

### ISSUE THREAD

**Issue by rusreh** [cmcpasserby/MayaCharm#28]
When I attempt to debug a script with the plugin I get the following:

`7:06 PM	MayaCharm: no running Maya Instance for "/mnt/tools/binlinux/aw/maya2016.5.sp2/bin/maya" found`
Even though my interpreter is set to:
`/mnt/tools/binlinux/aw/maya2016.5.sp2/bin/mayapy`

Where I am currently, the /maya script is a custom wrapper that then runs maya.bin.  It seems like this isn't looking for the maya.bin proc

**Comment by cmcpasserby** [comment]
@rusreh if you could let me know what the file names are for both `mayapy` and `maya`, and the relative path for `maya` from `mayapy` i am pretty sure i can get a new version out that works correctly on Linux

**Comment by rusreh** [comment]
So, yes maya is in /bin/maya.bin
For mayapy, it looks like mayapy is a wrapper which calls python-bin.  Both are also in /bin

**Comment by rusreh** [comment]
If you could release this is would be a massive help

**Comment by rusreh** [comment]
Any thought o when this might be available in Linux?  I'm looking forward to trying it out.

**Comment by cmcpasserby** [comment]
am pretty sure this is related to #44 and should be fixed very soon

**Comment by cmcpasserby** [comment]
closing this, since it might be fixed in the 3.2.x versions
