### ISSUE TITLE
Maya log does not work in PyCharm.

### ISSUE THREAD

**Issue by xmoner** [cmcpasserby/MayaCharm#29]
Log is working in maya but not in Pycharm. Is possible to get it work?

**Comment by xmoner** [comment]
awesome. I didn't know that there is a button for it. Many  thanks.

**Comment by cmcpasserby** [comment]
will leave this open for now, to remind myself to make this more obvious.
I have a button as opposed to do it when you execute a command since maya was not liking it when i spammed that command since it involves file IO
