### ISSUE TITLE
Can not debug if maya is started with command line arguments

### ISSUE THREAD

**Issue by pbiswal** [cmcpasserby/MayaCharm#30]
If maya is started with commandline arguments then the debug functionality in PyCharm does not work. It does not find the maya executable.

**Steps to Reproduce:**
1. Start Maya with the following command line parameter
`C:\Program Files\Autodesk\Maya 2017\bin\maya.exe -hideConsole`
2. Make sure correct command port is active in maya
3. Running a script from PyCharm works properly
4. Try debugging the script. It shows the following error.
`11:48 AM	MayaCharm: no running Maya Instance for "C:\Program Files\Autodesk\Maya2017\bin\maya.exe" found`

It seems like the it could be a bug in ProcessUtils in kotlin. Not sure. 

I am using the latest version of MayaCharm 3.0 with PyCharm Professional 2018.3 and Maya 2017 Update 5

**Comment by cmcpasserby** [comment]
Thanks, think it is more a error in how I poll for Maya processes, will look into it tonight

**Comment by cmcpasserby** [comment]
am pretty busy, but will try to submit the fix for this on the weekend

**Comment by cmcpasserby** [comment]
i fixed this in
d3d7d279aa892c7c8ca5a2a1c012b3c0cc13252c

will be in final once i merge that branch and submit to the plugin repo

**Comment by cmcpasserby** [comment]
this fix should be in the plugin repo in the next 2 to 3 days
