### ISSUE TITLE
Is it normal to get the list Active Maya SDK  empty

### ISSUE THREAD

**Issue by danielkenobi3d** [cmcpasserby/MayaCharm#31]
I am running maya 2017 and 2018 on windows 10.  And dont know what I am doing wrong or if I should install a maya SDK to make it work? I get the  list Active Maya SDK  empty.

**Comment by cmcpasserby** [comment]
Sorry it is not the most intuitive at the moment, am working to fix that once i have time.

Right now as long as you already added MayaPy for a maya install as a python interpreter, the maya install and port number should show up in that window. It might require closing and reopening the settings window for the change be applied and seen.

In the future once i have time and find the right api, i will have buttons for adding maya installs to this section where you can just point it at a install folder and it will find mayaPy and the maya executables on its own.

**Comment by danielkenobi3d** [comment]
I manage to add the mayapy.exe to the interpreter and I can see the maya SDK on the list and configure it but I dont get anything when I try to connect.
I echo all commands and I get this, but my file is not executing.
I am doing a print only
// Result: C:/Users/rende/Documents/maya/projects/default/untitled // 
untitledFileName();
// Result: untitled //

**Comment by danielkenobi3d** [comment]
some more debuging I am runing directly in maya console the following command 

execfile("D:\Development\RMPY\creators\spaceLocator.py")
the path is correct but I get exactly the same error.

execfile("D:\Development\RMPY\creators\spaceLocator.py")
file -q -exn;
// Result: C:/Users/rende/Documents/maya/projects/default/untitled // 
untitledFileName();
// Result: untitled // 
Any Idea if I broke something? I am asking because as soon as I added pycharm to the project interpreter,  pycharm started to do something.

**Comment by cmcpasserby** [comment]
did you add the startup code to maya so maya opens a command port on its startup

**Comment by danielkenobi3d** [comment]
Yes I didnt add it to the start, I run it on the terminal, and it is executing I can run the code but no stack trace if the script has errors.
