### ISSUE TITLE
Debugger Not working , breakpoint not riggered

### ISSUE THREAD

**Issue by sevelee** [cmcpasserby/MayaCharm#32]
pycharm version: 2018.3
mayacharm version: 3.0.1
maya version: 2018

I can execute file to maya var run/debug configurations in pycharm. But breakpoint just not work. The breakpoints won't trigger.
I comes with:
![image](https://user-images.githubusercontent.com/8036235/54023726-9d535d00-41d0-11e9-95d4-6dc078bd59e6.png)

![image](https://user-images.githubusercontent.com/8036235/54023650-74cb6300-41d0-11e9-88df-41b471baf496.png)
![image](https://user-images.githubusercontent.com/8036235/54023783-cecc2880-41d0-11e9-94dc-7c807e19b8d0.png)

**Comment by sevelee** [comment]
I also have pycharm 2018.2.7
I changed back to it and use mayacharm 2.1.6, use mayacharm debugger and it works.
So I think there is something wrong with pycharm 2018.3.5 and mayacharm 3.0.1
![image](https://user-images.githubusercontent.com/8036235/54029493-8833f980-41e3-11e9-9285-43a79d54a61e.png)

**Comment by cmcpasserby** [comment]
wont be able to look into things till the weekend, but yes newer versions of PyCharm removed the api the old version of MayaCharm uses so the 3.x versions are a complete rewrite that takes a very different approach to debugging.

**Comment by sevelee** [comment]
I also re-install my pycharm 2018.3.1 and mayacharm 3.0.0 to test but I just won't trigger the breakpoint.. 
![image](https://user-images.githubusercontent.com/8036235/54031196-09da5600-41e9-11e9-9fbf-51eb1d43f98e.png)
But I remember It should be work a few weeks ago, I have a memory that I used pycharm 2018.3 to debug some code.

Thanks for your contribution to this plugin 😄

**Comment by cmcpasserby** [comment]
yeah when i get home and take a look at it again, i might need to get you to test a few things, i only have access to older versions of maya

**Comment by sevelee** [comment]
Fell free to contact me for any testing. I have accesss to maya 2017 and 2017+ here.

**Comment by cmcpasserby** [comment]
so it looks to be working in my end with Maya 2016 PyCharm 2018.3 and the 3.0.1 version of the plugin.

can you show me what your settings panel for MayaCharm looks like, as well as your interpreter setup and run Config.

also try running `Run>Attach to process...` and tell me if your maya instance displays there and if it can attach that way.

**Comment by sevelee** [comment]
1. setting panel for mayaCharm:
![image](https://user-images.githubusercontent.com/8036235/54095287-728c2300-43e1-11e9-8c6f-280cdaf1afba.png)
2. interpreter setup:
![image](https://user-images.githubusercontent.com/8036235/54095299-8899e380-43e1-11e9-94ee-4eb5f5f5a384.png)
3. run config
![image](https://user-images.githubusercontent.com/8036235/54095392-0b22a300-43e2-11e9-99ad-c6ae5b12964d.png)
4. if I run "Attach to process...":
![image](https://user-images.githubusercontent.com/8036235/54095403-21c8fa00-43e2-11e9-8a01-6af34b9f943d.png)
5. Still not work now ...

**Comment by cmcpasserby** [comment]
i can't recreate often, but i have a few times now.
looks to be a bit of a race condition. where the command to execute code happens before the debugger si fully attached. noticed it only happens with simple scripts something more complex where i need to interact in maya before hitting a break point works.

so in a future version i will need to listen to see when Maya is ready, or add a longer delay(right now its 500ms)

**Comment by sevelee** [comment]
Is there a way that I can change 500ms to a longer time locally (in my computer) so that I can have a test?

**Comment by cmcpasserby** [comment]
not currently, it is a hard coded value but i am looking into a better way then just waiting. Also i don't think it would solve all of your issues, since manually attaching from the run menu also does not work for you.

**Comment by sevelee** [comment]
Well. I didn't change anything and works now. Looking for your next version to fix this. Thanks

**Comment by cmcpasserby** [comment]
yeah been too busy to spend any serious time on the plug-in. But for now the best work around is using `Attach To Process...` waiting for that to complete then clicking run on your config.

Its happening because right after attach, a bit of python code is executed to setup `PyDev`, and the code to execute in the process is running before that `PyDev` setup has returned.

can see what is going on, in these 2 files
[MayaCharmDebugRunner.kt](https://github.com/cmcpasserby/MayaCharm/blob/master/src/ca/rightsomegoodgames/mayacharm/run/MayaCharmDebugRunner.kt)
[MayaCharmDebugProcess.kt](https://github.com/cmcpasserby/MayaCharm/blob/master/src/ca/rightsomegoodgames/mayacharm/run/MayaCharmDebugProcess.kt)

more or less `afterConnect` gets called way to early.

**Comment by sevelee** [comment]
I get it. 
![image](https://user-images.githubusercontent.com/8036235/54503104-ada1cf80-4968-11e9-8273-7002bc20d416.png)
A little weird thing now is that sometimes the "Process finished with exit code 0 Server stopped." comes very quick so that I need to click run config very quick 😭

**Comment by cmcpasserby** [comment]
yeah there is some weirdness with Maya not always accepting it, when i get time i want to fix both of these issues, and make it so you can hit debug and it "just works" consistently but hard to find the time when i do primarily work with Maya or Python anymore

**Comment by sevelee** [comment]
I will see if I have sometime to change and test this plugin on my computer 👍

**Comment by ManaDork** [comment]
Question:   Having an inability to hit breakpoints also:  Tried multiple versions of PyCharm and MayaCharm based on combinations that people have reported success with and haven't been having much luck.  Running Maya 2018.5 (and wondering if its the culprit?)

If the console reports the Server stopped, when manually attaching to a Maya Process, that would mean that debug won't work?  (noob to IDE's)

**Comment by dseeni** [comment]
Did anyone figure this out? I occasionally get it to work and yet it most of the time it fails. What's a better remote debugger than PyCharm? Is there a alternate remote debugging setup?

**Comment by dseeni** [comment]
> I also have pycharm 2018.2.7
> I changed back to it and use mayacharm 2.1.6, use mayacharm debugger and it works.
> So I think there is something wrong with pycharm 2018.3.5 and mayacharm 3.0.1

I can confirm this works for me as well. Whew. I'm pretty new to all of this, so it's nice to have a working setting up at least. Very useful plugin, hopefully a fix can be made with to much trouble at some point.

**Comment by cmcpasserby** [comment]
this issue seems mostly tied to a race condition and only happens when debugging via a run configuration.

for now i am removing support for attaching the debugger via run config and just letting people do it manually via `Run/Attach to Process...` since it is more consistent and does not have the Maya code execute too early
