### ISSUE TITLE
Maya connection refused

### ISSUE THREAD

**Issue by chrisrogers3d** [cmcpasserby/MayaCharm#33]
I have attached to the maya process and started the command port.
I see execute in maya as a run configuration.

I can reach the commandport (from a browser, maya repeats the HTTP header) but when i try to execute in maya from pycharm I get a "Maya connection refused error"

I dont think its firewall related, my pycharm can connect to other servers.

**Comment by cmcpasserby** [comment]
is the command port open on the maya side, and do you have MayaCharm using the correct port number in its settings and finally in the run config is it targeting the right maya install

**Comment by chrisrogers3d** [comment]
Hey,
it was user error (i had the wrong port number)
Thanks!
