### ISSUE TITLE
REQUEST: Add 'Reload Document in Maya' menu command

### ISSUE THREAD

**Issue by earthtojens** [cmcpasserby/MayaCharm#35]
I would like to be able to reload the active PyCharm document in Maya. This would be very useful to allow me to modify Python and Mel documents in PyCharm and reload() OR source "" them in Maya without having to manually execute commands in the Maya script editor. This could hopefully be done by sending a command string to Maya in a similar way to how the current MayaCharm 'Execute Document in Maya' behaves.

**Preferred Behavior (pseudo code):**
If active PyCharm document is a Python file, import and reload in Maya to catch cases where the py file had not been imported yet:
```
import(<moduleName>)
reload(<moduleName>)
print "Reloaded <moduleName>"
```
If active PyCharm document is a Mel file, source it and print out what was sourced in Maya:
```
mel.eval('source "<melAbsPath>"');
print "Sourced <melAbsPath>";
```

**Comment by cmcpasserby** [comment]
if you create a new MayaCharm run configuration, you can select the `Execute Code` Section and just provide it with the code you want run when the configuration is run.

or if executing a whole file, you could add a `if __name__ == "__main__:"` section to the end of the file and provide any setup and tear down coded needed there.

**Comment by earthtojens** [comment]
> if you create a new MayaCharm run configuration, you can select the `Execute Code` Section and just provide it with the code you want run when the configuration is run.
> 
> or if executing a whole file, you could add a `if __name__ == "__main__:"` section to the end of the file and provide any setup and tear down coded needed there.

Thanks for the reply. In your experience is their a way to provide the current file path in the Execute code section via the PyCharm API? Having a menu item to do this would certainly be more convenient but i am certainly up for trying this strategy.
As for using the __name__ technique, I would rather avoid that in this context to prevent having to add it to every file I edit in PyCharm.

**Comment by cmcpasserby** [comment]
Yeah what you want is not all that hard to add for your exact use case. But the part that concerns me with just adding it is depending on how someones system is setup it would not work in a lot of cases and be highly dependent on where files live if they are in a python package or not.

**Comment by earthtojens** [comment]
That would certainly be disappointing to have it feel brittle and unreliable.
In my experience, being that MayaCharm remote debugging requires that the Maya Python environment sys.paths and the PyCharm project interpreter paths to overlap, wouldn't the 'reload document' success rate feel acceptable?
Under what cases do you see it failing that cause concern?
