### ISSUE TITLE
mayaCharm worked with pyCharm 2018 but not 2019

### ISSUE THREAD

**Issue by smeetdas** [cmcpasserby/MayaCharm#36]
I was using PyCharm 2018.2, and MayaCharm worked nicely.
Recently I upgraded to PyCharm 2019.2, and for some reason I can’t get PyCharm to to connect to Maya.  I’m on Windows, running maya 2018.5, PyCharm 2019.2, and MayaCharm 3.0.2
I get this error:
`   no running Maya Instance for "C:\Program Files\Autodesk\Maya2018\bin\maya.exe" found`

I am still able to debug using my old setup and MayaCharm 2018.2, so I was looking at the differences.  The old (working) configuration was of type "MayaCharm Runner".  This type doesn't exist any more, we have instead a "MayaCharm" configuration type with different information fields to fill in.  I don't know whether these types come from pyCharm or MayaCharm, so I'm attaching screen shots of the two.

Also I got a popup suggestion I install MayaCharm Debug Config Factory.  Sounds good but I don't know what that is and can't find it anywhere.  I attached the a screen grab of the popup.

If you know what I'm doing wrong, please let me know!

![factorPlugin](https://user-images.githubusercontent.com/53798907/62665960-2d3f3380-b936-11e9-8b4b-ed717d617158.PNG)
![OldWorkingDebug](https://user-images.githubusercontent.com/53798907/62665969-37613200-b936-11e9-90c3-ce8dcd4c782b.PNG)
![NewNotworkingDebug](https://user-images.githubusercontent.com/53798907/62665971-3af4b900-b936-11e9-8e9d-a3861a540877.PNG)

**Comment by cmcpasserby** [comment]
@mikebourbeauart yours looks like your project interpreter is set to a virtual env and not the mayaPy that matches your maya version

@smeetdas its best to delete the run configs and make them from scratch in your case. looks like you somehow have old run config data running on a new plugin
reopen if still a issue, in a few days 3.1.0 will come out which has a lot of bug fixes
