### ISSUE TITLE
No output from Print Statement 

### ISSUE THREAD

**Issue by kalkoby** [cmcpasserby/MayaCharm#37]
No output from Print statement when running in PyCharm using MayaCharm  I could create polygon objects from PyCharm to Maya but I'd like to have some output for its' translation information.    What did I miss it?

Using a simple print statement ("Hello World" )  did not show up on debug console nor file.

**Comment by cmcpasserby** [comment]
from the run menu did you select `Connect to Maya's Log` yet?
Running that should tell Maya to start logging to file where the plugin can read and display the output in PyCharm.
