### ISSUE TITLE
Mayacharm no longer working in debug mode for Pycharm 2019.2

### ISSUE THREAD

**Issue by ben-hearn-sb** [cmcpasserby/MayaCharm#38]
After ugrading to PyCharm 2019.2 Debug mode no longer works.

Non-debug mode is fine but debug produces the following errors in this order:

```
# Traceback (most recent call last):
# TypeError: 'NoneType' object is not callable
#     r = r.decode('utf-8')
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\_pydevd_bundle\pydevd_comm.py", line 294, in _on_run
#     r = r.decode('utf-8')
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\_pydevd_bundle\pydevd_comm.py", line 294, in _on_run
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\_pydevd_bundle\pydevd_comm.py", line 199, in run


# Traceback (most recent call last):
# TypeError: 'NoneType' object is not callable
#     try:
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\pydevd.py", line 133, in _on_run
#     try:
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\pydevd.py", line 133, in _on_run
#     def run(self):
# TypeError: 'NoneType' object is not callable
#     self.py_db.check_output_redirect()
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\pydevd.py", line 175, in _on_run
#     self.py_db.check_output_redirect()
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\pydevd.py", line 175, in _on_run
#     def run(self):
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\_pydevd_bundle\pydevd_comm.py", line 199, in run

# Traceback (most recent call last):
# TypeError: 'NoneType' object is not callable
#     r = r.decode('utf-8')
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\_pydevd_bundle\pydevd_comm.py", line 294, in _on_run
#     r = r.decode('utf-8')
#   File "C:/Program Files/JetBrains/PyCharm 2019.2/helpers/pydev\_pydevd_bundle\pydevd_comm.py", line 294, in _on_run
```

**Comment by sethfrolich** [comment]
I'm having this exact issue as well. The debugger has stopped successfully connecting and now displays the above error inside Maya. This started happening at some time within the last two weeks. Sadly, I can't be any more specific than that.

**Comment by ben-hearn-sb** [comment]
I have downgraded to PyCharm 2018 and its working again but the debugger hangs indefinitely for some time before having to restart Maya and trying again

**Comment by ben-hearn-sb** [comment]
Breakpoints are also very rarely being hit. The __init__ function appears to be particularly problematic

**Comment by cmcpasserby** [comment]
hmm odd, i wont have much time to look in the next few weeks since i am going on vacation soon and need to catch up at work first.

The not working in 2019 issue i will need to look at, the breakpoints sometimes not being hit issue i think is a race condition between the debugger and the command port. More or less it sends the command before the debugger is fully attached. A work around for this for now could be manually attaching the debugger via the `Run > Attach to Process` menu. As long as the plugin is working Maya should display in the regular attach to process dialog just like a normal python process.

Other thing to look at would be, is PyCharm setup to use the same mayapy that matches the maya you are trying to debug.

**Comment by ben-hearn-sb** [comment]
No dice on the attach to process, that does not attach at all.

I have had to roll back to 2018.2 to get the old setup back a nd now I have no problems.

Did you or they change the debuging processes durin gthe updates?

**Comment by sethfrolich** [comment]
Mine would begin the attach to process and then the error message from the beginning of the thread would show up in Maya. I didn't have to revert nearly as far to get the debugger working again, though. I just had to step back to PyCharm 2019.1.4

**Comment by cmcpasserby** [comment]
things are working pretty stable on my end with attach to process. using PyCharm 2019.2 and Maya 2016. so once that version makes it to the plugin repo in a few days i am curious to here if there is any change for anyone.

**Comment by cmcpasserby** [comment]
going to need to make lots of changes to how things work in newer versions, so just watch #43
