### ISSUE TITLE
Runtime error R6034

### ISSUE THREAD

**Issue by elmagnificogi** [cmcpasserby/MayaCharm#39]
Runtime error
i use maya 2017 with pycharm 2019.2
it's my first time use the mayacharm.
when i Attaching to maya or Debug maya 
All will make maya.exe report a Runtime error R6034

i could Run the code,no error
Debug the code ,Runtime error R6034

i try manually connet the debugger
when i import pydevd_pycharm ,Runtime error R6034
so is there something wrong with me or just the pydevd_pycharm ?
Also i pip the pydevd_pycharm in mayapy.exe,is there anything wrong?

when the maya report the Runtime error R6034,it doesn't crash,just work as usual.
when you try again,it wont show anything,but the breakpoint not work the debug not work

**Comment by cmcpasserby** [comment]
you should not need to pip install anything. but the debug runner has been having problems in newer versions.

does it work as expected if you attach manually first via "Attach To Process" in the run menu?

**Comment by elmagnificogi** [comment]
> does it work as expected if you attach manually first via "Attach To Process" in the run menu?

not work,it will poll a error,i forgot it

**Comment by cmcpasserby** [comment]
when 3.1.0 comes out could you let me know if this is still a issue?

**Comment by cmcpasserby** [comment]
reopen if its not fixed in 3.1.0
