### ISSUE TITLE
unicode cant work

### ISSUE THREAD

**Issue by elmagnificogi** [cmcpasserby/MayaCharm#41]
`confirm = cmds.confirmDialog(title='更新', icon='warning', message="更新前请确定已经保存好场景了",button=['是','否'],defaultButton='否', cancelButton='否',dismissString='否')`

code like this,i use chinese or japanese that in unicode,then i run it from pyCharm
the maya output

> line 1: SyntaxError: file <maya console> line 1: Non-ASCII character '\xb8' in file C:/Users/ELMAGN~1/AppData/Local/Temp/MayaCharmTemp12387148987302551673.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details # 

if i just use the command in maya script,it work fine.

so maybe could u add a unicode ,gbk or some other encode method in pluggin settings？

**Comment by cmcpasserby** [comment]
i should be able to look into this on the weekend, looks like when i create the temp file i can just include the encoding string at the top and it will just work again.

**Comment by cmcpasserby** [comment]
was this happening when executing just the selection or the whole file?

**Comment by elmagnificogi** [comment]
> was this happening when executing just the selection or the whole file?

selection

**Comment by cmcpasserby** [comment]
the next update will always add the utf8 encoding string to selections that are executed. Reopen of it is still a issue in a few days when the 3.1.0 version comes out
435bf44b75c1532294b08290a9ea2e1b9f54b066
