### ISSUE TITLE
Attach to process launched by batch file.

### ISSUE THREAD

**Issue by YKdvd** [cmcpasserby/MayaCharm#44]
Windows 10, PyCharm 2019.2.5 Professional, MayaCharm 3.1.1, Maya 2019.

If I launch Maya 2019 directly (double-click on maya.exe, or from search bar or any other method), in PyCharm the Run->Attach to Process... command finds it, shows it in a separate ----Maya-- section as "1234567 maya", etc.

But our studio pipeline launches Maya from a batch file, from a line like "C:\Program Files\Autodesk\maya2019\bin\maya.exe".  In this case, Attach to Process does not see it, although Task Manager doesn't seem to show any obvious difference in the two Maya processes - Process name and Command line are identical, for instance.

Is there something about how MayaCharm looks for Maya processes that would be failing in the batch-launch scenario?

**Comment by cmcpasserby** [comment]
going to look into this one, now for the next updates, it is most likely tied to this line
https://github.com/cmcpasserby/MayaCharm/blob/3e90cd99f9001cb360548ef8fe6aef5c8a2dca72/src/ca/rightsomegoodgames/mayacharm/debugattach/MayaAttachDebuggerProvider.kt#L26

which is a hack to get around processInfo not returning the proper path.

**Comment by cmcpasserby** [comment]
though example script that recreates the problem would be great

**Comment by YKdvd** [comment]
It would be great if this could work again, as we set up our production environment in the batch file and launch Maya, and there doesn't seem to be a way to attach to an arbitrary PID in PyCharm's "Run->Attach to Process..."?  The core batch file (say, "batch2.bat") does something like this:
```
set _PARM=
SET _MAYA_EXE_PATH=C:\Program Files\Autodesk\maya%1\bin\maya.exe
SET _CMDLINE="%_MAYA_EXE_PATH%" %_PARM%
echo %_CMDLINE%
:: now do our launch command
 %_CMDLINE%
```
and gets called from various batch files (say, batch1.bat) with a Maya version (and other parameters) like this:
`CALL batch2.bat 2016`
and MayaCharm fails to find the Maya launched this way with or without the "CALL" as part of calling batch file.

**Comment by cmcpasserby** [comment]
yeah managed to find the issue. Upside is that it is really easy to fix, downside is i will need a implementation for each OS.

**Comment by cmcpasserby** [comment]
So i submitted a new version that targets PyCharm 2019.2 and has fixes to ensure it can still correctly find Maya processes that were created via script. Should take about 2 days to be approved and up on the Plugin repository for install.

**Comment by YKdvd** [comment]
Great, I'll trying installing from the github assets, and if that doesn't work I'll wait for it to show up at JetBrain.

**Comment by YKdvd** [comment]
I pulled this from github, and hooray, Attach To Process now finds Maya 2016SP6 when launched from our Windows batchfile launchers, and successfully hit a breakpoint. Maya 2020 also seems to work.
Thanks muchly!
