### ISSUE TITLE
MayaCharm Log Issue

### ISSUE THREAD

**Issue by enriquevelmai** [cmcpasserby/MayaCharm#45]
Hi Chris,
Under Maya 2019.2, Maya Charm 3.1.1, mayapy.exe as sdk and Window 10 as operative system: maya log inside PyCharm does not show logger.debug("msg") and logger.info("msg"), . Does I need to consider something more?
I do not know if is a configuration problem or the way is coded the getting of the loggers.

**Comment by cmcpasserby** [comment]
logging is based on the output file created by this command.
https://download.autodesk.com/us/maya/2011help/CommandsPython/cmdFileOutput.html

have seen a few issues, and i have been looking at a better way but that is all dependent on if i can get the plugin working again with PyCharm 2019.3 and its changes to the debugger.

**Comment by enriquevelmai** [comment]
Thanks Chris :D
