### ISSUE TITLE
Exception happens after code execution

### ISSUE THREAD

**Issue by cyberiRex** [cmcpasserby/MayaCharm#47]
Pycharm 2019.2 .2.4 . MayaCharm version 3.1.2. OS Windows 10

Hi Chris!
After code execution I get this exception. The code executes correctly but  this exception crashes Maya with our custom Log UI opened. Any Idea why this exception happens? 

```
Exception happened during processing of request from ('127.0.0.1', 50156)
# Traceback (most recent call last):
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\SocketServer.py", line 295, in _handle_request_noblock
#     self.process_request(request, client_address)
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\SocketServer.py", line 321, in process_request
#     self.finish_request(request, client_address)
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\SocketServer.py", line 334, in finish_request
#     self.RequestHandlerClass(request, client_address, self)
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\SocketServer.py", line 657, in __init__
#     self.finish()
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\SocketServer.py", line 716, in finish
#     self.wfile.close()
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\socket.py", line 283, in close
#     self.flush()
#   File "C:\Program Files\Autodesk\Maya2019\bin\python27.zip\socket.py", line 307, in flush
#     self._sock.sendall(view[write_offset:write_offset+buffer_size])
# error: [Errno 10053] An established connection was aborted by the software in your host machine
```

**Comment by cmcpasserby** [comment]
Sorry for being late on this, how does your custom Log UI work, when MayaCharm executes something in Maya, it will sometimes also make calls to `cmds.cmdFileOutput` so it can pipe the log into a file as well for its own use.

Is this always happening or only while the debugger is Attached?

**Comment by cyberiRex** [comment]
Thanks for reply. 
Basically our tool is for filtering and classifying maya’s log. It uses Maya Python API callback and updates PySide Widget. We are using MCommandMessage callback. 

It does not happening always. Only when Maya takes relatively long time to update viewport after code execution.

**Comment by cmcpasserby** [comment]
have been some pretty large changes for the 3.2.x version so am closing for now, can reopen if issue is reproduced again.
