### ISSUE TITLE
Maya Log window not working on Linux based system

### ISSUE THREAD

**Issue by joksim** [cmcpasserby/MayaCharm#5]
The log window not working on linux based system. No text is shown as output of the commands (for example the output shown in the script editor)

Using fedora 23 with maya 2016 SP3, and using openjdk version "1.8.0_91"

**Comment by ilbozo** [comment]
Same issue here using centos. Any solution for that? Thanks
Ale

**Comment by ilbozo** [comment]
Just noticed that the txt file gets populated, wondering where is the issue...

**Comment by ilbozo** [comment]
Another thing. It seems the txt file should be named mayaLog.txt but the one that gets created has a lowercase L (mayalog.txt). Maybe it's a hint...

**Comment by ilbozo** [comment]
Ok i tried to soft link mayalog.txt to mayaLog.txt and it works!

**Comment by ilbozo** [comment]
It seems to be a typo in MayaCommInterface.java line 113

**Comment by cmcpasserby** [comment]
i will take a look when i get home later today, since i dont have maya at home. Is Linux case sensitive , most of my testing has been on osx and windows

**Comment by cmcpasserby** [comment]
Your right it is a typo, but the typo is in `MayaLogConsole.java` line 39 i will fix that when i get home.
Also a other consideration to make, is i built this with the JDK from oracle and use some more modern Java 8 features in my code. Im not exactly sure what level of java openJDK supports.

**Comment by ilbozo** [comment]
I found it as well on the file i told you, dunno if it's relevant! The only thing i noticed is that the output seems to be redundant. The txt file should be flushed every time but i guess is already done by your plugin, maybe the typo will fix everything!

**Comment by cmcpasserby** [comment]
is this still a issue after the latest version?
