### ISSUE TITLE
PyCharm Professional required?

### ISSUE THREAD

**Issue by YKdvd** [cmcpasserby/MayaCharm#50]
Is PyCharm Professional still required for MayaCharm?  In theory, the Community edition can "Attach to Process..." to a local (not remote) process, but doesn't know how to detect Maya's "mayapy" as a running Python process to attach to?  Does whatever MayaCharm's addition into Pycharm's process discovery routines still require Professional?

Out of curiosity, what criteria does stock PyCharm use to find eligible local processes to Attach... to?

**Comment by cmcpasserby** [comment]
Pro version is not required anymore, has been that way for almost 2 years now, since version 3.0.0.
though as you can see from issue #43 all of the debugging features have broke on PyCharm 2019.3 and above. The latest PyCharm version that has all features working is 2019.2

**Comment by YKdvd** [comment]
Thanks, I wasn't sure - the README.md, and the text on the JetBrains page, still have "_For users of the professional version of PyCharm it will also setup and connect the pydev debugger to Maya as well_"

**Comment by cmcpasserby** [comment]
ah, i will have to update those, to say otherwise then
