### ISSUE TITLE
MayaCharm runner not found

### ISSUE THREAD

**Issue by tstex** [cmcpasserby/MayaCharm#52]
Hi

I have a Mayacharm project called Maya2018. All of the debug UI in PyCharm is greyed out, and I am getting this error:

Error running 'Maya2018': Cannot find runner for Maya2018

I should add that I originally had Pycharm 2020.1 installed, and was then advised that I needed PyCharm 2019.2.4 installed to run MayaCharm, and something about downgrading PyCharm broke things for me, but I'm unclear what that might be. I've tried uninstallling and reinstalling - but that does not seem to fix it. 

Any idea what that might be, or how to fix it?

Thanks!

**Comment by cmcpasserby** [comment]
closing for now, the 3.2.x version when release might fix this, and at the very least will let you use it on modern versions of PyCharm
