### ISSUE TITLE
Debug pauses at line 92 threading.py & MayaCharmTemp.py

### ISSUE THREAD

**Issue by ben-hearn-sb** [cmcpasserby/MayaCharm#6]
Not sure if I have incorrect setup but nearly everytime I send commands to Maya in Debug mode using MayaCharm my debugger pauses at threading.py line 92 and at pydev.settrace in the MayaCharm temp file.

Any suggestions on how to avoid this as it is quite annoying?

Cheers,

Ben

**Comment by cmcpasserby** [comment]
Do you have "Suspend after connect" checked off in the run config options? If so you may want to uncheck that.

**Comment by ben-hearn-sb** [comment]
Hell cmcpasserby,

"Suspend after connect" is indeed off for all of my debug configs. On initial tests it does not seem to pause at the MayaCharm temp file but it still pauses at the settrace.py file

- Ben

**Comment by cmcpasserby** [comment]
So can you give some information about your configuration, what OS you are running what version of PyCharm and what Version of Maya?

I have not been able to recreat this issue on my setup, and for me it only stops at the settrace line of the temp file if i have "Suspend after connect" checked off.

Also maybe try providing me with a usecase and file that recreats it for you.
