### ISSUE TITLE
Update plugin for PyCharm 2021.2 release.

### ISSUE THREAD

**Issue by chadlichty** [cmcpasserby/MayaCharm#60]
I am hoping this is just a setting and an easy change.

**Comment by cmcpasserby** [comment]
Yeah it should just be a few changes to the `gradle.properties` and a quick test just need to target the new SDK. I might find time tonight to start that and if not the weekend.

**Comment by chadlichty** [comment]
Thanks!

**Comment by cmcpasserby** [comment]
its approved and out now

**Comment by chadlichty** [comment]
sweet Thanks!
