### ISSUE TITLE
It seems that UTF-8 is not supported when using Python 3.

### ISSUE THREAD

**Issue by miysugi** [cmcpasserby/MayaCharm#69]
(I report on behalf of the plugin user.)

The error related to character encoding occurs in Maya when using python3. On the other hand, there are no issues when using python2. 

`# Error: line 1: ValueError: file C:/Users/user44/work/PycharmProjects/selfMade_04/test_py3.py line 13: Single '}' encountered in format string #`
<img width="734" alt="error" src="https://github.com/cmcpasserby/MayaCharm/assets/3774618/1b85a04c-a0f4-4c61-a48f-e7e1031a807f">

### Steps to reproduce:
1. install MayaCharm plugin in PyCharm
2. write python code in PyCharm
3. create a batch file to set python3 for Maya
4. conduct remote execution via MayaCharm plugin in PyCharm
5. When using python3 and including the multibyte characters, the error occurs in Maya, despite '`# -*- coding: utf-8 -*-`' is written in the code.

### Information:
When executing it using command on the same environment, the error does not occur. So, we think the problem happens via MayaCharm plugin.

### Version:
- PyCharm: 2023.2.1
- MayaCharm plugin: 3.2.6
- Maya: 2022

### Sample code:
```
# -*- coding: utf-8 -*-

def test():
    print(u'hello')

if __name__ == '__main__':
    print('{}.py: loaded as script file'.format(__name__))
    test()
else:
    print('{}.py: loaded as module file'.format(__name__))
    print('{}'.format(__file__))  

print(u'モジュール名{}\n'.format(__name__)) 

```
### Attached files:
- Batch file for Maya to set python3(Step3)
![batchForPython3](https://github.com/cmcpasserby/MayaCharm/assets/3774618/53f0bb0a-9a88-4726-91f3-07fa8e5b72be)
- Maya Screen with batch file applied
![mayaPython3Version](https://github.com/cmcpasserby/MayaCharm/assets/3774618/b1616e8b-d9fd-4dea-8ddb-5edd0dc3503a)
- Execution by command line<img width="1044" alt="command" src="https://github.com/cmcpasserby/MayaCharm/assets/3774618/adffc465-8c0b-4216-b7ac-394626fa4012">

**Comment by cmcpasserby** [comment]
Was not able to test in Maya, but was able to recreate the problem in isolation and is related to the encoding when building this string to execute.
https://github.com/cmcpasserby/MayaCharm/blob/87229d12228161b66a3d5564aa89c94fd00d2a0c/src/main/kotlin/resources/PythonStrings.kt#L11

This should be a very simple fix, so i will try and find some time to deal with it on the weekend and submit a new build to the marketplace.

**Comment by cmcpasserby** [comment]
https://github.com/cmcpasserby/MayaCharm/releases/tag/v.3.2.7
This release should fix the issue, will take a few days to make it to the marketplace, but if it can be tested with this use case that would be great.

**Comment by 44hero** [comment]
I’ve been  heavily depending on this plugin, and it need to be resolved to keep PyCharm / MayaCharm running.

**Comment by 44hero** [comment]
Thank you very much for your response to our request for correction.
We hope that you will be able to finish the correction and release the product.
Thank you very much.
If the author had not responded, I would have been at a loss, with no one to turn to,
I would have given up using PyCham in the future, and even thought of migrating to VSCode.
Thank you so much.
You are the one to count on.

From far away Japan

**Comment by cmcpasserby** [comment]
version 3.2.7 is not out on the plugins marketplace, so will close this issue for now and reopen if anyone is still having text encoding issues on this version.

**Comment by 44hero** [comment]
Thank you so much.
I look forward to having you upload 3.2.7 to Market Place.

**Comment by 44hero** [comment]
Today is noon Japan time.
I received the latest MayaCharm 3.2.7 Plug-in update notification on the Marketplace.
I quickly checked to see if it worked properly.
It has been successfully executed without any problems.

Thank you very much for your response.

thank you! !

far from Japan

**Comment by 44hero** [comment]
maya2022's py2 and py3 systems, both
Getting MayaCharm to work properly is more difficult than I expected.
Thank you very much for always responding well.

Thank you for your continued support.

far from Japan
