### ISSUE TITLE
Simply doesn't work, and doesn't give any error messages

### ISSUE THREAD

**Issue by NeuroMonk** [cmcpasserby/MayaCharm#7]
I use PyCharm Community Edition 5.0.2 and Maya2014/2016.
"Connects to Maya's log" does nothing.  Alt+S or Alt+A also do nothing. Nothing is happened. No error messages, no log messages. No success messages. Nothing.

**Comment by NeuroMonk** [comment]
In mayaCharm i have:

**Comment by NeuroMonk** [comment]
Up! Waiting for an update. Really want to switch to pycharm from sublime.

**Comment by alexwidener** [comment]
This usually happens whenever the port is in use (I run through the same range of ports frequently and have to manually change them when they conflict). Sorry for reviving a closed issue, but I saw it and thought it might help somebody new to MayaCharm. 😄
